// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package numberverifier.proxies;

public class Phone_type
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject phone_typeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NumberVerifier.Phone_type";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Mobile("Mobile"),
		Fixed_line("Fixed_line"),
		Fixed_line_or_mobile("Fixed_line_or_mobile"),
		Voip("Voip"),
		Toll_free("Toll_free"),
		Premium_rate("Premium_rate"),
		Standard_rate("Standard_rate"),
		Shared_cost("Shared_cost"),
		Personal("Personal"),
		Pager("Pager"),
		Voicemail("Voicemail"),
		Shortcode("Shortcode"),
		Emergency("Emergency"),
		Unknown("Unknown"),
		Phone_type_Response("NumberVerifier.Phone_type_Response");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Phone_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NumberVerifier.Phone_type"));
	}

	protected Phone_type(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject phone_typeMendixObject)
	{
		if (phone_typeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NumberVerifier.Phone_type", phone_typeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NumberVerifier.Phone_type");

		this.phone_typeMendixObject = phone_typeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Phone_type.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static numberverifier.proxies.Phone_type initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return numberverifier.proxies.Phone_type.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static numberverifier.proxies.Phone_type initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new numberverifier.proxies.Phone_type(context, mendixObject);
	}

	public static numberverifier.proxies.Phone_type load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return numberverifier.proxies.Phone_type.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Mobile
	 */
	public final java.lang.Boolean getMobile()
	{
		return getMobile(getContext());
	}

	/**
	 * @param context
	 * @return value of Mobile
	 */
	public final java.lang.Boolean getMobile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Mobile.toString());
	}

	/**
	 * Set value of Mobile
	 * @param mobile
	 */
	public final void setMobile(java.lang.Boolean mobile)
	{
		setMobile(getContext(), mobile);
	}

	/**
	 * Set value of Mobile
	 * @param context
	 * @param mobile
	 */
	public final void setMobile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean mobile)
	{
		getMendixObject().setValue(context, MemberNames.Mobile.toString(), mobile);
	}

	/**
	 * @return value of Fixed_line
	 */
	public final java.lang.Boolean getFixed_line()
	{
		return getFixed_line(getContext());
	}

	/**
	 * @param context
	 * @return value of Fixed_line
	 */
	public final java.lang.Boolean getFixed_line(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Fixed_line.toString());
	}

	/**
	 * Set value of Fixed_line
	 * @param fixed_line
	 */
	public final void setFixed_line(java.lang.Boolean fixed_line)
	{
		setFixed_line(getContext(), fixed_line);
	}

	/**
	 * Set value of Fixed_line
	 * @param context
	 * @param fixed_line
	 */
	public final void setFixed_line(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean fixed_line)
	{
		getMendixObject().setValue(context, MemberNames.Fixed_line.toString(), fixed_line);
	}

	/**
	 * @return value of Fixed_line_or_mobile
	 */
	public final java.lang.Boolean getFixed_line_or_mobile()
	{
		return getFixed_line_or_mobile(getContext());
	}

	/**
	 * @param context
	 * @return value of Fixed_line_or_mobile
	 */
	public final java.lang.Boolean getFixed_line_or_mobile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Fixed_line_or_mobile.toString());
	}

	/**
	 * Set value of Fixed_line_or_mobile
	 * @param fixed_line_or_mobile
	 */
	public final void setFixed_line_or_mobile(java.lang.Boolean fixed_line_or_mobile)
	{
		setFixed_line_or_mobile(getContext(), fixed_line_or_mobile);
	}

	/**
	 * Set value of Fixed_line_or_mobile
	 * @param context
	 * @param fixed_line_or_mobile
	 */
	public final void setFixed_line_or_mobile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean fixed_line_or_mobile)
	{
		getMendixObject().setValue(context, MemberNames.Fixed_line_or_mobile.toString(), fixed_line_or_mobile);
	}

	/**
	 * @return value of Voip
	 */
	public final java.lang.Boolean getVoip()
	{
		return getVoip(getContext());
	}

	/**
	 * @param context
	 * @return value of Voip
	 */
	public final java.lang.Boolean getVoip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Voip.toString());
	}

	/**
	 * Set value of Voip
	 * @param voip
	 */
	public final void setVoip(java.lang.Boolean voip)
	{
		setVoip(getContext(), voip);
	}

	/**
	 * Set value of Voip
	 * @param context
	 * @param voip
	 */
	public final void setVoip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean voip)
	{
		getMendixObject().setValue(context, MemberNames.Voip.toString(), voip);
	}

	/**
	 * @return value of Toll_free
	 */
	public final java.lang.Boolean getToll_free()
	{
		return getToll_free(getContext());
	}

	/**
	 * @param context
	 * @return value of Toll_free
	 */
	public final java.lang.Boolean getToll_free(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Toll_free.toString());
	}

	/**
	 * Set value of Toll_free
	 * @param toll_free
	 */
	public final void setToll_free(java.lang.Boolean toll_free)
	{
		setToll_free(getContext(), toll_free);
	}

	/**
	 * Set value of Toll_free
	 * @param context
	 * @param toll_free
	 */
	public final void setToll_free(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toll_free)
	{
		getMendixObject().setValue(context, MemberNames.Toll_free.toString(), toll_free);
	}

	/**
	 * @return value of Premium_rate
	 */
	public final java.lang.Boolean getPremium_rate()
	{
		return getPremium_rate(getContext());
	}

	/**
	 * @param context
	 * @return value of Premium_rate
	 */
	public final java.lang.Boolean getPremium_rate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Premium_rate.toString());
	}

	/**
	 * Set value of Premium_rate
	 * @param premium_rate
	 */
	public final void setPremium_rate(java.lang.Boolean premium_rate)
	{
		setPremium_rate(getContext(), premium_rate);
	}

	/**
	 * Set value of Premium_rate
	 * @param context
	 * @param premium_rate
	 */
	public final void setPremium_rate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean premium_rate)
	{
		getMendixObject().setValue(context, MemberNames.Premium_rate.toString(), premium_rate);
	}

	/**
	 * @return value of Standard_rate
	 */
	public final java.lang.Boolean getStandard_rate()
	{
		return getStandard_rate(getContext());
	}

	/**
	 * @param context
	 * @return value of Standard_rate
	 */
	public final java.lang.Boolean getStandard_rate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Standard_rate.toString());
	}

	/**
	 * Set value of Standard_rate
	 * @param standard_rate
	 */
	public final void setStandard_rate(java.lang.Boolean standard_rate)
	{
		setStandard_rate(getContext(), standard_rate);
	}

	/**
	 * Set value of Standard_rate
	 * @param context
	 * @param standard_rate
	 */
	public final void setStandard_rate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean standard_rate)
	{
		getMendixObject().setValue(context, MemberNames.Standard_rate.toString(), standard_rate);
	}

	/**
	 * @return value of Shared_cost
	 */
	public final java.lang.Boolean getShared_cost()
	{
		return getShared_cost(getContext());
	}

	/**
	 * @param context
	 * @return value of Shared_cost
	 */
	public final java.lang.Boolean getShared_cost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Shared_cost.toString());
	}

	/**
	 * Set value of Shared_cost
	 * @param shared_cost
	 */
	public final void setShared_cost(java.lang.Boolean shared_cost)
	{
		setShared_cost(getContext(), shared_cost);
	}

	/**
	 * Set value of Shared_cost
	 * @param context
	 * @param shared_cost
	 */
	public final void setShared_cost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shared_cost)
	{
		getMendixObject().setValue(context, MemberNames.Shared_cost.toString(), shared_cost);
	}

	/**
	 * @return value of Personal
	 */
	public final java.lang.Boolean getPersonal()
	{
		return getPersonal(getContext());
	}

	/**
	 * @param context
	 * @return value of Personal
	 */
	public final java.lang.Boolean getPersonal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Personal.toString());
	}

	/**
	 * Set value of Personal
	 * @param personal
	 */
	public final void setPersonal(java.lang.Boolean personal)
	{
		setPersonal(getContext(), personal);
	}

	/**
	 * Set value of Personal
	 * @param context
	 * @param personal
	 */
	public final void setPersonal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean personal)
	{
		getMendixObject().setValue(context, MemberNames.Personal.toString(), personal);
	}

	/**
	 * @return value of Pager
	 */
	public final java.lang.Boolean getPager()
	{
		return getPager(getContext());
	}

	/**
	 * @param context
	 * @return value of Pager
	 */
	public final java.lang.Boolean getPager(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Pager.toString());
	}

	/**
	 * Set value of Pager
	 * @param pager
	 */
	public final void setPager(java.lang.Boolean pager)
	{
		setPager(getContext(), pager);
	}

	/**
	 * Set value of Pager
	 * @param context
	 * @param pager
	 */
	public final void setPager(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean pager)
	{
		getMendixObject().setValue(context, MemberNames.Pager.toString(), pager);
	}

	/**
	 * @return value of Voicemail
	 */
	public final java.lang.Boolean getVoicemail()
	{
		return getVoicemail(getContext());
	}

	/**
	 * @param context
	 * @return value of Voicemail
	 */
	public final java.lang.Boolean getVoicemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Voicemail.toString());
	}

	/**
	 * Set value of Voicemail
	 * @param voicemail
	 */
	public final void setVoicemail(java.lang.Boolean voicemail)
	{
		setVoicemail(getContext(), voicemail);
	}

	/**
	 * Set value of Voicemail
	 * @param context
	 * @param voicemail
	 */
	public final void setVoicemail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean voicemail)
	{
		getMendixObject().setValue(context, MemberNames.Voicemail.toString(), voicemail);
	}

	/**
	 * @return value of Shortcode
	 */
	public final java.lang.Boolean getShortcode()
	{
		return getShortcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Shortcode
	 */
	public final java.lang.Boolean getShortcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Shortcode.toString());
	}

	/**
	 * Set value of Shortcode
	 * @param shortcode
	 */
	public final void setShortcode(java.lang.Boolean shortcode)
	{
		setShortcode(getContext(), shortcode);
	}

	/**
	 * Set value of Shortcode
	 * @param context
	 * @param shortcode
	 */
	public final void setShortcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shortcode)
	{
		getMendixObject().setValue(context, MemberNames.Shortcode.toString(), shortcode);
	}

	/**
	 * @return value of Emergency
	 */
	public final java.lang.Boolean getEmergency()
	{
		return getEmergency(getContext());
	}

	/**
	 * @param context
	 * @return value of Emergency
	 */
	public final java.lang.Boolean getEmergency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Emergency.toString());
	}

	/**
	 * Set value of Emergency
	 * @param emergency
	 */
	public final void setEmergency(java.lang.Boolean emergency)
	{
		setEmergency(getContext(), emergency);
	}

	/**
	 * Set value of Emergency
	 * @param context
	 * @param emergency
	 */
	public final void setEmergency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean emergency)
	{
		getMendixObject().setValue(context, MemberNames.Emergency.toString(), emergency);
	}

	/**
	 * @return value of Unknown
	 */
	public final java.lang.Boolean getUnknown()
	{
		return getUnknown(getContext());
	}

	/**
	 * @param context
	 * @return value of Unknown
	 */
	public final java.lang.Boolean getUnknown(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Unknown.toString());
	}

	/**
	 * Set value of Unknown
	 * @param unknown
	 */
	public final void setUnknown(java.lang.Boolean unknown)
	{
		setUnknown(getContext(), unknown);
	}

	/**
	 * Set value of Unknown
	 * @param context
	 * @param unknown
	 */
	public final void setUnknown(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean unknown)
	{
		getMendixObject().setValue(context, MemberNames.Unknown.toString(), unknown);
	}

	/**
	 * @return value of Phone_type_Response
	 */
	public final numberverifier.proxies.Response getPhone_type_Response() throws com.mendix.core.CoreException
	{
		return getPhone_type_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone_type_Response
	 */
	public final numberverifier.proxies.Response getPhone_type_Response(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		numberverifier.proxies.Response result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Phone_type_Response.toString());
		if (identifier != null)
			result = numberverifier.proxies.Response.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Phone_type_Response
	 * @param phone_type_response
	 */
	public final void setPhone_type_Response(numberverifier.proxies.Response phone_type_response)
	{
		setPhone_type_Response(getContext(), phone_type_response);
	}

	/**
	 * Set value of Phone_type_Response
	 * @param context
	 * @param phone_type_response
	 */
	public final void setPhone_type_Response(com.mendix.systemwideinterfaces.core.IContext context, numberverifier.proxies.Response phone_type_response)
	{
		if (phone_type_response == null)
			getMendixObject().setValue(context, MemberNames.Phone_type_Response.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Phone_type_Response.toString(), phone_type_response.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return phone_typeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final numberverifier.proxies.Phone_type that = (numberverifier.proxies.Phone_type) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NumberVerifier.Phone_type";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
