// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package numberverifier.proxies;

public class Response
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NumberVerifier.Response";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Carrier("Carrier"),
		Country_code("Country_code"),
		Country_iso("Country_iso"),
		Format_e164("Format_e164"),
		Format_international("Format_international"),
		Format_national("Format_national"),
		Ported("Ported"),
		Region("Region"),
		Region_code("Region_code"),
		Active_number("Active_number"),
		Carrier_mcc("Carrier_mcc"),
		Carrier_mnc("Carrier_mnc"),
		Roaming("Roaming"),
		Valid_number("Valid_number"),
		HasError("HasError"),
		ErrorMessage("ErrorMessage"),
		Roaming_carrier("Roaming_carrier"),
		Roaming_country_iso("Roaming_country_iso"),
		Roaming_country_prefix("Roaming_country_prefix"),
		Roaming_mcc("Roaming_mcc"),
		Roaming_mnc("Roaming_mnc"),
		Phone_type_Response("NumberVerifier.Phone_type_Response");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NumberVerifier.Response"));
	}

	protected Response(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject)
	{
		if (responseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NumberVerifier.Response", responseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NumberVerifier.Response");

		this.responseMendixObject = responseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Response.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static numberverifier.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return numberverifier.proxies.Response.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static numberverifier.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new numberverifier.proxies.Response(context, mendixObject);
	}

	public static numberverifier.proxies.Response load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return numberverifier.proxies.Response.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Carrier
	 */
	public final java.lang.String getCarrier()
	{
		return getCarrier(getContext());
	}

	/**
	 * @param context
	 * @return value of Carrier
	 */
	public final java.lang.String getCarrier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Carrier.toString());
	}

	/**
	 * Set value of Carrier
	 * @param carrier
	 */
	public final void setCarrier(java.lang.String carrier)
	{
		setCarrier(getContext(), carrier);
	}

	/**
	 * Set value of Carrier
	 * @param context
	 * @param carrier
	 */
	public final void setCarrier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String carrier)
	{
		getMendixObject().setValue(context, MemberNames.Carrier.toString(), carrier);
	}

	/**
	 * @return value of Country_code
	 */
	public final java.lang.Integer getCountry_code()
	{
		return getCountry_code(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_code
	 */
	public final java.lang.Integer getCountry_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Country_code.toString());
	}

	/**
	 * Set value of Country_code
	 * @param country_code
	 */
	public final void setCountry_code(java.lang.Integer country_code)
	{
		setCountry_code(getContext(), country_code);
	}

	/**
	 * Set value of Country_code
	 * @param context
	 * @param country_code
	 */
	public final void setCountry_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer country_code)
	{
		getMendixObject().setValue(context, MemberNames.Country_code.toString(), country_code);
	}

	/**
	 * @return value of Country_iso
	 */
	public final java.lang.String getCountry_iso()
	{
		return getCountry_iso(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_iso
	 */
	public final java.lang.String getCountry_iso(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country_iso.toString());
	}

	/**
	 * Set value of Country_iso
	 * @param country_iso
	 */
	public final void setCountry_iso(java.lang.String country_iso)
	{
		setCountry_iso(getContext(), country_iso);
	}

	/**
	 * Set value of Country_iso
	 * @param context
	 * @param country_iso
	 */
	public final void setCountry_iso(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country_iso)
	{
		getMendixObject().setValue(context, MemberNames.Country_iso.toString(), country_iso);
	}

	/**
	 * @return value of Format_e164
	 */
	public final java.lang.String getFormat_e164()
	{
		return getFormat_e164(getContext());
	}

	/**
	 * @param context
	 * @return value of Format_e164
	 */
	public final java.lang.String getFormat_e164(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Format_e164.toString());
	}

	/**
	 * Set value of Format_e164
	 * @param format_e164
	 */
	public final void setFormat_e164(java.lang.String format_e164)
	{
		setFormat_e164(getContext(), format_e164);
	}

	/**
	 * Set value of Format_e164
	 * @param context
	 * @param format_e164
	 */
	public final void setFormat_e164(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String format_e164)
	{
		getMendixObject().setValue(context, MemberNames.Format_e164.toString(), format_e164);
	}

	/**
	 * @return value of Format_international
	 */
	public final java.lang.String getFormat_international()
	{
		return getFormat_international(getContext());
	}

	/**
	 * @param context
	 * @return value of Format_international
	 */
	public final java.lang.String getFormat_international(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Format_international.toString());
	}

	/**
	 * Set value of Format_international
	 * @param format_international
	 */
	public final void setFormat_international(java.lang.String format_international)
	{
		setFormat_international(getContext(), format_international);
	}

	/**
	 * Set value of Format_international
	 * @param context
	 * @param format_international
	 */
	public final void setFormat_international(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String format_international)
	{
		getMendixObject().setValue(context, MemberNames.Format_international.toString(), format_international);
	}

	/**
	 * @return value of Format_national
	 */
	public final java.lang.String getFormat_national()
	{
		return getFormat_national(getContext());
	}

	/**
	 * @param context
	 * @return value of Format_national
	 */
	public final java.lang.String getFormat_national(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Format_national.toString());
	}

	/**
	 * Set value of Format_national
	 * @param format_national
	 */
	public final void setFormat_national(java.lang.String format_national)
	{
		setFormat_national(getContext(), format_national);
	}

	/**
	 * Set value of Format_national
	 * @param context
	 * @param format_national
	 */
	public final void setFormat_national(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String format_national)
	{
		getMendixObject().setValue(context, MemberNames.Format_national.toString(), format_national);
	}

	/**
	 * @return value of Ported
	 */
	public final java.lang.Boolean getPorted()
	{
		return getPorted(getContext());
	}

	/**
	 * @param context
	 * @return value of Ported
	 */
	public final java.lang.Boolean getPorted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Ported.toString());
	}

	/**
	 * Set value of Ported
	 * @param ported
	 */
	public final void setPorted(java.lang.Boolean ported)
	{
		setPorted(getContext(), ported);
	}

	/**
	 * Set value of Ported
	 * @param context
	 * @param ported
	 */
	public final void setPorted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ported)
	{
		getMendixObject().setValue(context, MemberNames.Ported.toString(), ported);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of Region_code
	 */
	public final java.lang.String getRegion_code()
	{
		return getRegion_code(getContext());
	}

	/**
	 * @param context
	 * @return value of Region_code
	 */
	public final java.lang.String getRegion_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region_code.toString());
	}

	/**
	 * Set value of Region_code
	 * @param region_code
	 */
	public final void setRegion_code(java.lang.String region_code)
	{
		setRegion_code(getContext(), region_code);
	}

	/**
	 * Set value of Region_code
	 * @param context
	 * @param region_code
	 */
	public final void setRegion_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region_code)
	{
		getMendixObject().setValue(context, MemberNames.Region_code.toString(), region_code);
	}

	/**
	 * @return value of Active_number
	 */
	public final java.lang.Boolean getActive_number()
	{
		return getActive_number(getContext());
	}

	/**
	 * @param context
	 * @return value of Active_number
	 */
	public final java.lang.Boolean getActive_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active_number.toString());
	}

	/**
	 * Set value of Active_number
	 * @param active_number
	 */
	public final void setActive_number(java.lang.Boolean active_number)
	{
		setActive_number(getContext(), active_number);
	}

	/**
	 * Set value of Active_number
	 * @param context
	 * @param active_number
	 */
	public final void setActive_number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active_number)
	{
		getMendixObject().setValue(context, MemberNames.Active_number.toString(), active_number);
	}

	/**
	 * @return value of Carrier_mcc
	 */
	public final java.lang.String getCarrier_mcc()
	{
		return getCarrier_mcc(getContext());
	}

	/**
	 * @param context
	 * @return value of Carrier_mcc
	 */
	public final java.lang.String getCarrier_mcc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Carrier_mcc.toString());
	}

	/**
	 * Set value of Carrier_mcc
	 * @param carrier_mcc
	 */
	public final void setCarrier_mcc(java.lang.String carrier_mcc)
	{
		setCarrier_mcc(getContext(), carrier_mcc);
	}

	/**
	 * Set value of Carrier_mcc
	 * @param context
	 * @param carrier_mcc
	 */
	public final void setCarrier_mcc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String carrier_mcc)
	{
		getMendixObject().setValue(context, MemberNames.Carrier_mcc.toString(), carrier_mcc);
	}

	/**
	 * @return value of Carrier_mnc
	 */
	public final java.lang.String getCarrier_mnc()
	{
		return getCarrier_mnc(getContext());
	}

	/**
	 * @param context
	 * @return value of Carrier_mnc
	 */
	public final java.lang.String getCarrier_mnc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Carrier_mnc.toString());
	}

	/**
	 * Set value of Carrier_mnc
	 * @param carrier_mnc
	 */
	public final void setCarrier_mnc(java.lang.String carrier_mnc)
	{
		setCarrier_mnc(getContext(), carrier_mnc);
	}

	/**
	 * Set value of Carrier_mnc
	 * @param context
	 * @param carrier_mnc
	 */
	public final void setCarrier_mnc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String carrier_mnc)
	{
		getMendixObject().setValue(context, MemberNames.Carrier_mnc.toString(), carrier_mnc);
	}

	/**
	 * @return value of Roaming
	 */
	public final java.lang.Boolean getRoaming()
	{
		return getRoaming(getContext());
	}

	/**
	 * @param context
	 * @return value of Roaming
	 */
	public final java.lang.Boolean getRoaming(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Roaming.toString());
	}

	/**
	 * Set value of Roaming
	 * @param roaming
	 */
	public final void setRoaming(java.lang.Boolean roaming)
	{
		setRoaming(getContext(), roaming);
	}

	/**
	 * Set value of Roaming
	 * @param context
	 * @param roaming
	 */
	public final void setRoaming(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean roaming)
	{
		getMendixObject().setValue(context, MemberNames.Roaming.toString(), roaming);
	}

	/**
	 * @return value of Valid_number
	 */
	public final java.lang.Boolean getValid_number()
	{
		return getValid_number(getContext());
	}

	/**
	 * @param context
	 * @return value of Valid_number
	 */
	public final java.lang.Boolean getValid_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Valid_number.toString());
	}

	/**
	 * Set value of Valid_number
	 * @param valid_number
	 */
	public final void setValid_number(java.lang.Boolean valid_number)
	{
		setValid_number(getContext(), valid_number);
	}

	/**
	 * Set value of Valid_number
	 * @param context
	 * @param valid_number
	 */
	public final void setValid_number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean valid_number)
	{
		getMendixObject().setValue(context, MemberNames.Valid_number.toString(), valid_number);
	}

	/**
	 * @return value of HasError
	 */
	public final java.lang.Boolean getHasError()
	{
		return getHasError(getContext());
	}

	/**
	 * @param context
	 * @return value of HasError
	 */
	public final java.lang.Boolean getHasError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasError.toString());
	}

	/**
	 * Set value of HasError
	 * @param haserror
	 */
	public final void setHasError(java.lang.Boolean haserror)
	{
		setHasError(getContext(), haserror);
	}

	/**
	 * Set value of HasError
	 * @param context
	 * @param haserror
	 */
	public final void setHasError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haserror)
	{
		getMendixObject().setValue(context, MemberNames.HasError.toString(), haserror);
	}

	/**
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage()
	{
		return getErrorMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorMessage.toString());
	}

	/**
	 * Set value of ErrorMessage
	 * @param errormessage
	 */
	public final void setErrorMessage(java.lang.String errormessage)
	{
		setErrorMessage(getContext(), errormessage);
	}

	/**
	 * Set value of ErrorMessage
	 * @param context
	 * @param errormessage
	 */
	public final void setErrorMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errormessage)
	{
		getMendixObject().setValue(context, MemberNames.ErrorMessage.toString(), errormessage);
	}

	/**
	 * @return value of Roaming_carrier
	 */
	public final java.lang.String getRoaming_carrier()
	{
		return getRoaming_carrier(getContext());
	}

	/**
	 * @param context
	 * @return value of Roaming_carrier
	 */
	public final java.lang.String getRoaming_carrier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Roaming_carrier.toString());
	}

	/**
	 * Set value of Roaming_carrier
	 * @param roaming_carrier
	 */
	public final void setRoaming_carrier(java.lang.String roaming_carrier)
	{
		setRoaming_carrier(getContext(), roaming_carrier);
	}

	/**
	 * Set value of Roaming_carrier
	 * @param context
	 * @param roaming_carrier
	 */
	public final void setRoaming_carrier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roaming_carrier)
	{
		getMendixObject().setValue(context, MemberNames.Roaming_carrier.toString(), roaming_carrier);
	}

	/**
	 * @return value of Roaming_country_iso
	 */
	public final java.lang.String getRoaming_country_iso()
	{
		return getRoaming_country_iso(getContext());
	}

	/**
	 * @param context
	 * @return value of Roaming_country_iso
	 */
	public final java.lang.String getRoaming_country_iso(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Roaming_country_iso.toString());
	}

	/**
	 * Set value of Roaming_country_iso
	 * @param roaming_country_iso
	 */
	public final void setRoaming_country_iso(java.lang.String roaming_country_iso)
	{
		setRoaming_country_iso(getContext(), roaming_country_iso);
	}

	/**
	 * Set value of Roaming_country_iso
	 * @param context
	 * @param roaming_country_iso
	 */
	public final void setRoaming_country_iso(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roaming_country_iso)
	{
		getMendixObject().setValue(context, MemberNames.Roaming_country_iso.toString(), roaming_country_iso);
	}

	/**
	 * @return value of Roaming_country_prefix
	 */
	public final java.lang.String getRoaming_country_prefix()
	{
		return getRoaming_country_prefix(getContext());
	}

	/**
	 * @param context
	 * @return value of Roaming_country_prefix
	 */
	public final java.lang.String getRoaming_country_prefix(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Roaming_country_prefix.toString());
	}

	/**
	 * Set value of Roaming_country_prefix
	 * @param roaming_country_prefix
	 */
	public final void setRoaming_country_prefix(java.lang.String roaming_country_prefix)
	{
		setRoaming_country_prefix(getContext(), roaming_country_prefix);
	}

	/**
	 * Set value of Roaming_country_prefix
	 * @param context
	 * @param roaming_country_prefix
	 */
	public final void setRoaming_country_prefix(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roaming_country_prefix)
	{
		getMendixObject().setValue(context, MemberNames.Roaming_country_prefix.toString(), roaming_country_prefix);
	}

	/**
	 * @return value of Roaming_mcc
	 */
	public final java.lang.String getRoaming_mcc()
	{
		return getRoaming_mcc(getContext());
	}

	/**
	 * @param context
	 * @return value of Roaming_mcc
	 */
	public final java.lang.String getRoaming_mcc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Roaming_mcc.toString());
	}

	/**
	 * Set value of Roaming_mcc
	 * @param roaming_mcc
	 */
	public final void setRoaming_mcc(java.lang.String roaming_mcc)
	{
		setRoaming_mcc(getContext(), roaming_mcc);
	}

	/**
	 * Set value of Roaming_mcc
	 * @param context
	 * @param roaming_mcc
	 */
	public final void setRoaming_mcc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roaming_mcc)
	{
		getMendixObject().setValue(context, MemberNames.Roaming_mcc.toString(), roaming_mcc);
	}

	/**
	 * @return value of Roaming_mnc
	 */
	public final java.lang.String getRoaming_mnc()
	{
		return getRoaming_mnc(getContext());
	}

	/**
	 * @param context
	 * @return value of Roaming_mnc
	 */
	public final java.lang.String getRoaming_mnc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Roaming_mnc.toString());
	}

	/**
	 * Set value of Roaming_mnc
	 * @param roaming_mnc
	 */
	public final void setRoaming_mnc(java.lang.String roaming_mnc)
	{
		setRoaming_mnc(getContext(), roaming_mnc);
	}

	/**
	 * Set value of Roaming_mnc
	 * @param context
	 * @param roaming_mnc
	 */
	public final void setRoaming_mnc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roaming_mnc)
	{
		getMendixObject().setValue(context, MemberNames.Roaming_mnc.toString(), roaming_mnc);
	}

	/**
	 * @return value of Phone_type_Response
	 */
	public final numberverifier.proxies.Phone_type getPhone_type_Response() throws com.mendix.core.CoreException
	{
		return getPhone_type_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone_type_Response
	 */
	public final numberverifier.proxies.Phone_type getPhone_type_Response(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		numberverifier.proxies.Phone_type result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Phone_type_Response.toString());
		if (identifier != null)
			result = numberverifier.proxies.Phone_type.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Phone_type_Response
	 * @param phone_type_response
	 */
	public final void setPhone_type_Response(numberverifier.proxies.Phone_type phone_type_response)
	{
		setPhone_type_Response(getContext(), phone_type_response);
	}

	/**
	 * Set value of Phone_type_Response
	 * @param context
	 * @param phone_type_response
	 */
	public final void setPhone_type_Response(com.mendix.systemwideinterfaces.core.IContext context, numberverifier.proxies.Phone_type phone_type_response)
	{
		if (phone_type_response == null)
			getMendixObject().setValue(context, MemberNames.Phone_type_Response.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Phone_type_Response.toString(), phone_type_response.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final numberverifier.proxies.Response that = (numberverifier.proxies.Response) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NumberVerifier.Response";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
