// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package numberverifier.proxies;

public class Timezone
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject timezoneMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NumberVerifier.Timezone";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timezone("Timezone"),
		Timezone_Response("NumberVerifier.Timezone_Response");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Timezone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NumberVerifier.Timezone"));
	}

	protected Timezone(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject timezoneMendixObject)
	{
		if (timezoneMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NumberVerifier.Timezone", timezoneMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NumberVerifier.Timezone");

		this.timezoneMendixObject = timezoneMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Timezone.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static numberverifier.proxies.Timezone initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return numberverifier.proxies.Timezone.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static numberverifier.proxies.Timezone initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new numberverifier.proxies.Timezone(context, mendixObject);
	}

	public static numberverifier.proxies.Timezone load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return numberverifier.proxies.Timezone.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone()
	{
		return getTimezone(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Timezone.toString());
	}

	/**
	 * Set value of Timezone
	 * @param timezone
	 */
	public final void setTimezone(java.lang.String timezone)
	{
		setTimezone(getContext(), timezone);
	}

	/**
	 * Set value of Timezone
	 * @param context
	 * @param timezone
	 */
	public final void setTimezone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.Timezone.toString(), timezone);
	}

	/**
	 * @return value of Timezone_Response
	 */
	public final numberverifier.proxies.Response getTimezone_Response() throws com.mendix.core.CoreException
	{
		return getTimezone_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone_Response
	 */
	public final numberverifier.proxies.Response getTimezone_Response(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		numberverifier.proxies.Response result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Timezone_Response.toString());
		if (identifier != null)
			result = numberverifier.proxies.Response.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Timezone_Response
	 * @param timezone_response
	 */
	public final void setTimezone_Response(numberverifier.proxies.Response timezone_response)
	{
		setTimezone_Response(getContext(), timezone_response);
	}

	/**
	 * Set value of Timezone_Response
	 * @param context
	 * @param timezone_response
	 */
	public final void setTimezone_Response(com.mendix.systemwideinterfaces.core.IContext context, numberverifier.proxies.Response timezone_response)
	{
		if (timezone_response == null)
			getMendixObject().setValue(context, MemberNames.Timezone_Response.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Timezone_Response.toString(), timezone_response.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return timezoneMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final numberverifier.proxies.Timezone that = (numberverifier.proxies.Timezone) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NumberVerifier.Timezone";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
