// This file was generated by Mendix Modeler 7.3.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package numberverifier.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the NumberVerifier module

	public static java.lang.String getCMLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NumberVerifier.CMLogNode");
	}

	/**
	* without /
	*/
	public static java.lang.String getEndpointURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NumberVerifier.EndpointURL");
	}

	/**
	*  Get your token here: https://register.cmtelecom.com/en
	*/
	public static java.lang.String getProductToken()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NumberVerifier.ProductToken");
	}
}